# Generated by Django 5.0.4 on 2024-05-03 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcoment',
            options={'verbose_name': 'نظر محصول', 'verbose_name_plural': 'نظرات محصولات'},
        ),
        migrations.AlterField(
            model_name='productcoment',
            name='autour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productcoment',
            name='purches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productcoment',
            name='text',
            field=models.TextField(verbose_name='متن'),
        ),
    ]
