# Generated by Django 5.0.4 on 2024-05-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_alter_productcoment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcoment',
            name='is_accepted',
            field=models.BooleanField(null=True, verbose_name='رد / قبول'),
        ),
    ]
