# Generated by Django 5.0.4 on 2024-05-03 01:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productcoment_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcoment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ'),
            preserve_default=False,
        ),
    ]
