# Generated by Django 5.0.4 on 2024-05-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCommentFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام کاربری')),
                ('email_address', models.EmailField(max_length=300, verbose_name='ایمیل کاربر')),
                ('text', models.TextField(verbose_name='متن نظر')),
            ],
            options={
                'verbose_name': 'ایحاد نظر مقاله',
                'verbose_name_plural': 'ابحاد نظرات مقاله',
            },
        ),
    ]
